(function(g){var window=this;var joa=function(a){if(!a.Fa||!a.Fa.annotations)return null;a=g.p(a.Fa.annotations);for(var b=a.next();!b.done;b=a.next())if(b=b.value,b.playerAnnotationsExpandedRenderer&&b.playerAnnotationsExpandedRenderer.featuredChannel)return b.playerAnnotationsExpandedRenderer.featuredChannel;return null},W_=function(a){a.i||(a.i=new g.xn,g.H(a,a.i));
return a.i},X_=function(a){a.N("cardstatechange",g.iK(a)&&g.jK(a)?1:0)},koa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Pi&&a.dataset){if(g.jc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.ed("pollChoiceIndex"))},loa=function(a){return Math.pow(a,3)},moa=function(a){return 3*a*a-2*a*a*a},Y_=function(a,b){(0,g.z)(b,function(c){c={csn:a,
ve:g.rA(c),eventType:4};var d={Xi:void 0,ih:a};"UNDEFINED_CSN"==a?g.CA("visualElementShown",c,d):g.qr("visualElementShown",c,g.vr,d)})},Z_=function(a,b){(0,g.z)(b,function(c){var d=void 0;
d=void 0===d?!1:d;c={csn:a,ve:g.rA(c),eventType:d?16:8};d={Xi:void 0,ih:a,uB:d};"UNDEFINED_CSN"==a?g.CA("visualElementHidden",c,d):g.qr("visualElementHidden",c,g.vr,d)})},b0=function(a){a=g.Qa(a);
delete $_[a];g.Zb($_)&&a0&&a0.stop()},c0=function(){a0||(a0=new g.I(function(){noa()},20));
var a=a0;a.isActive()||a.start()},noa=function(){var a=(0,g.A)();
g.Mb($_,function(b){d0(b,a)});
g.Zb($_)||c0()},e0=function(a,b,c,d){g.mn.call(this);
if(!g.La(a)||!g.La(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.l=a;this.G=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.D=0;this.B=null},d0=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.B);a.B=b;f0(a,a.progress);1==a.progress?(a.g=0,b0(a),a.Wc(),a.o()):1==a.g&&a.Vq()},f0=function(a,b){g.Na(a.C)&&(b=a.C(b));
a.coords=Array(a.l.length);for(var c=0;c<a.l.length;c++)a.coords[c]=(a.G[c]-a.l[c])*b+a.l[c]},g0=function(a,b){g.Xj.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},h0=function(a,b,c,d,e){e0.call(this,b,c,d,e);
this.element=a},i0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
h0.call(this,a,b,c,d,e)},j0=function(a){g.F.call(this);
this.i=a||window;this.g=[]},ooa=function(a,b,c,d){c=(0,g.x)(c,d||a.i);
b=g.gr(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},k0=function(a){return a.baseUrl||null},poa=function(a,b,c){function d(Y){var ia=Y.hovercardButton;
if(!ia)return null;ia=ia.subscribeButtonRenderer;if(!ia)return null;var Ha=f(ia.unsubscribedButtonText),md=f(ia.subscribedButtonText);if(ia.subscribed){var Uc=f(ia.subscriberCountWithUnsubscribeText);var $g=f(ia.subscriberCountText)}else Uc=f(ia.subscriberCountText),$g=f(ia.subscriberCountWithSubscribeText);var nd=null;return Y.signinEndpoint&&(nd=g.Ub(Y,"signinEndpoint","webNavigationEndpointData","url"),!nd)?null:Ha&&(md||nd)?{subscribed:ia.subscribed,subscribeText:Ha,subscribeCount:Uc,unsubscribeText:md,
unsubscribeCount:$g,enabled:ia.enabled,signinUrl:nd,classic:Y.useClassicSubscribeButton}:null}
function e(Y){if(Y){var ia=[],Ha=Y.videoId;Ha&&ia.push("v="+Ha);(Ha=Y.playlistId)&&ia.push("list="+Ha);(Y=Y.startTimeSeconds)&&ia.push("t="+Y);return"/watch?"+ia.join("&")}}
function f(Y){if(!Y)return null;var ia=Y.simpleText;return ia?ia:Y.runs?(0,g.ee)(Y.runs,function(Ha){return Ha.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,v=null,y=null,B=!1,C=null,G=null,J=null,E=null,M=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,v=f(b.playlistLength);else if("CHANNEL"==k){if(B=g.Ub(l,"browseEndpoint","browseId"))y=B,m="/channel/"+y;n=!1;q="new";(B=!!b.isSubscribe)?C=d(b):G=f(b.subscribersText)}else"WEBSITE"==
k?((J=g.Ub(l,"urlEndpoint","url"))&&(m=J),n=!0,q="new",J=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&b.additionalFeesText&&(E=f(b.productPrice),M=f(b.additionalFeesText)),(a=g.Ub(l,"urlEndpoint","url"))&&(m=a),n=!0,q="new");a=g.Ub(b,"title","accessibility","accessibilityData","label");return{id:"element-"+c,type:k,title:f(b.title),metadata:f(b.metadata),callToAction:f(b.callToAction),hu:b.image,iconUrl:J,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),
aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:v,channelId:y,subscribeButton:C,subscribersText:G,isSubscribe:B,targetUrl:m,OC:n,Db:{itct:b.trackingParams},vL:q,Li:a?a:null,SC:b.isPlaceholder,impressionUrls:(0,g.ee)(b.impressionUrls||[],k0),FC:(0,g.ee)(b.hovercardShowUrls||[],k0),clickUrls:(0,g.ee)(l.loggingUrls||[],k0),visualElement:g.qA(b.trackingParams),productPrice:E,additionalFeesText:M}},l0=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=(0,g.ee)(a.impressionUrls||[],k0);c.skip=a.skipEndscreen;a.trackingParams&&(c.visualElement=g.qA(a.trackingParams));var d=(0,g.ee)(a.elements||[],function(e,f){return poa(b,e,f)});
c.elements=(0,g.Vd)(d,function(e){return!!e});
return c},m0=function(a){g.QO.call(this,a);
this.i=null;this.D=!1;this.o=null;this.g={};this.B={};this.w=this.l=null;this.G=[];a=a.L();this.I=g.Jy(a)||g.Ly(a);this.R=!0;this.C=0;this.u=new g.Is(this);g.H(this,this.u);this.u.J(this.player,g.sD("creatorendscreen"),this.yD);this.u.J(this.player,"crx_creatorendscreen",this.zD);this.u.J(this.player,"resize",this.Na);this.u.J(window,"focus",this.vK);this.load();var b=g.Pd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.zi(this,function(){g.Ud(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},n0=function(a){return a.player.getVideoData().Wb?"current":a.I?"new":"current"},o0=function(a){return"creator-endscreen-editor"===a.player.L().playerStyle},p0=function(a,b){g.UP(a.player.app,"creatorendscreen",void 0);
a.l&&(a.l.dispose(),a.l=null,a.w.dispose(),a.w=null);for(var c in a.g)a.g[c].dispose();a.g={};a.B={};0<a.G.length&&(a.G.forEach(function(l){l.dispose()}),a.G.length=0);
a.C=0;if((a.i=b)&&b.elements){qoa(a);c=[];var d=new g.pD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.L().g||(a.l=new g.T({A:"div",F:"ytp-ce-shadow"}),g.tK(a.player,a.l.element,4),a.w=new g.eL(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=roa(a,e);a.g[e.id]=f;a.B[e.id]=e;g.tK(a.player,f.element,4);var k=new g.pD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);soa(a,f,e)}g.pK(a.player,
c);a.Na()}},qoa=function(a){var b=g.LA(),c=g.MA();
c&&b&&a.i.visualElement&&g.DA(c,b,[a.i.visualElement],void 0)},roa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={A:"div",U:["ytp-ce-element","ytp-ce-video"],K:{tabindex:"0","aria-label":b.Li||"","aria-hidden":"true"},H:[{A:"div",F:"ytp-ce-element-shadow"},{A:"div",F:"ytp-ce-covering-image",K:q0(b)},{A:"div",F:"ytp-ce-covering-shadow-top"},{A:"a",F:"ytp-ce-covering-overlay",K:{href:r0(a,b.targetUrl),tabindex:"-1"},H:[{A:"div",U:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],K:{dir:g.qn(b.title||"")},T:b.title},{A:"div",F:"ytp-ce-video-duration",T:b.videoDuration}]}]};
c=new g.T(c);break;case "PLAYLIST":c={A:"div",U:["ytp-ce-element","ytp-ce-playlist"],K:{tabindex:"0","aria-label":b.Li||"","aria-hidden":"true"},H:[{A:"div",F:"ytp-ce-element-shadow"},{A:"div",F:"ytp-ce-covering-image",K:q0(b)},{A:"div",F:"ytp-ce-covering-shadow-top"},{A:"a",F:"ytp-ce-covering-overlay",K:{href:r0(a,b.targetUrl),tabindex:"-1"},H:[{A:"div",U:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],K:{dir:g.qn(b.title||"")},T:b.title},{A:"div",F:"ytp-ce-playlist-count",H:[{A:"div",
F:"ytp-ce-playlist-icon"},{A:"div",F:"ytp-ce-playlist-count-text",T:b.playlistLength}]}]}]};c=new g.T(c);break;case "CHANNEL":c={A:"div",U:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],K:{tabindex:"0","aria-label":b.Li||"","aria-hidden":"true"},H:[{A:"div",F:"ytp-ce-element-shadow"},{A:"div",F:"ytp-ce-expanding-overlay",H:[{A:"div",F:"ytp-ce-expanding-overlay-hider"},{A:"div",F:"ytp-ce-expanding-overlay-background"},{A:"div",F:"ytp-ce-expanding-overlay-content",
H:[{A:"div",F:"ytp-ce-expanding-overlay-body",H:[{A:"div",F:"ytp-ce-expanding-overlay-body-padding",H:[{A:"a",U:["ytp-ce-channel-title","ytp-ce-link"],K:{href:r0(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.qn(b.title||"")},T:b.title},b.subscribeButton?{A:"div",F:"ytp-ce-subscribe-container",H:[{A:"div",F:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{A:"div",F:"ytp-ce-channel-subscribers-text",T:b.subscribersText}:"",b.metadata?{A:"div",U:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
T:b.metadata}:""]}]}]}]},{A:"div",F:"ytp-ce-expanding-image",K:q0(b)}]};c=new g.T(c);var d=g.Cd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.L().g){var e=null;var f=b.Db.itct}else e="endscreen",f=null;e=new g.$P(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.G.push(e)}break;case "WEBSITE":c={A:"div",U:["ytp-ce-element","ytp-ce-website"],K:{tabindex:"0","aria-label":b.Li||"","aria-hidden":"true"},H:[{A:"div",F:"ytp-ce-element-shadow"},{A:"div",F:"ytp-ce-expanding-overlay",H:[{A:"div",F:"ytp-ce-expanding-overlay-hider"},{A:"div",F:"ytp-ce-expanding-overlay-background"},{A:"div",F:"ytp-ce-expanding-overlay-content",H:[{A:"div",F:"ytp-ce-expanding-overlay-body",
H:[{A:"div",F:"ytp-ce-expanding-overlay-body-padding",H:[{A:"div",F:"ytp-ce-website-title",K:{dir:g.qn(b.title||"")},T:b.title},{A:"div",F:"ytp-ce-website-metadata",T:b.metadata},{A:"a",U:["ytp-ce-website-goto","ytp-ce-link"],K:{href:r0(a,b.targetUrl),target:"_blank",tabindex:"-1"},T:b.callToAction}]}]}]}]},{A:"div",F:"ytp-ce-expanding-image",K:q0(b)},{A:"div",F:"ytp-ce-expanding-icon",K:s0(b.iconUrl)}]};c=new g.T(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&b.additionalFeesText&&(c={A:"div",
F:"ytp-ce-merchandise-price-container",H:[{A:"div",F:"ytp-ce-merchandise-price",T:b.productPrice},{A:"div",F:"ytp-ce-merchandise-additional-fees",T:b.additionalFeesText}]}),c={A:"div",U:["ytp-ce-element","ytp-ce-merchandise"],K:{tabindex:"0","aria-label":b.Li||"","aria-hidden":"true"},H:[{A:"div",F:"ytp-ce-element-shadow"},{A:"div",F:"ytp-ce-expanding-overlay",H:[{A:"div",F:"ytp-ce-expanding-overlay-hider"},{A:"div",F:"ytp-ce-expanding-overlay-background"},{A:"div",F:"ytp-ce-expanding-overlay-content",
H:[{A:"div",F:"ytp-ce-expanding-overlay-body",H:[{A:"div",F:"ytp-ce-expanding-overlay-body-padding",H:[{A:"div",F:"ytp-ce-merchandise-title",K:{dir:g.qn(b.title||"")},T:b.title},c,{A:"div",F:"ytp-ce-merchandise-metadata",T:b.metadata},{A:"div",F:"ytp-ce-merchandise-expanded-cta-container",H:[{A:"a",U:["ytp-ce-merchandise-goto","ytp-ce-link"],K:{href:r0(a,b.targetUrl),target:"_blank",tabindex:"-1"},T:b.callToAction},{A:"div",F:"ytp-ce-merchandise-cta-external"}]}]}]}]}]},{A:"div",F:"ytp-ce-expanding-image",
K:q0(b)},{A:"div",F:"ytp-ce-merchandise-invideo-cta-container",H:[{A:"div",F:"ytp-ce-merchandise-invideo-cta",T:b.callToAction}]}]},c=new g.T(c)}b.SC&&g.K(c.element,"ytp-ce-placeholder");return c},q0=function(a){if(a.hu)var b=a.hu.thumbnails;
return s0(b?b[b.length-1].url:null)},s0=function(a){return a?{style:"background-image: url("+a+")"}:{}},soa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ea("mouseenter",(0,g.x)(a.lq,a,b,c));b.ea("mouseleave",(0,g.x)(a.ar,a,b,c));a.player.L().g||b.ea("click",(0,g.x)(function(l){g.K(l.element,"ytp-ce-element-hover")},a,b));
b.ea("click",(0,g.x)(a.Hx,a,c));b.ea("keypress",(0,g.x)(a.Hx,a,c));b.ea("focus",(0,g.x)(function(l,m){this.lq(l,m)},a,b,c));
b.ea("blur",(0,g.x)(function(l,m){this.ar(l,m)},a,b,c));
b.ea("touchstart",(0,g.x)(a.lq,a,b,c));var f=g.Ed("ytp-ce-expanding-overlay-hider",b.element);f&&b.J(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.kn(b.element,"ytp-ce-element-hover");g.kn(b.element,"ytp-ce-force-expand")});
b.ea("keydown",(0,g.x)(function(l,m){this.R=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.C+=n;0<this.C?(g.K(l.element,"ytp-ce-force-expand"),t0(this,m.id,!0)):(g.kn(l.element,"ytp-ce-force-expand"),g.kn(l.element,"ytp-ce-element-hover"),t0(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ea("blur",g.Ra(function(){"none"!=m.style.display&&a.R&&m.focus()})),l.J(m,"focus",d),l.J(m,"blur",e))},a,b);
c(g.Ed("ytp-sb-subscribe",b.element));c(g.Ed("ytp-sb-unsubscribe",b.element));b.ea("focus",d);b.ea("blur",e)},r0=function(a,b){var c=a.player.L();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.mz(c)+b}else return"";return b},t0=function(a,b,c){a.l&&(c?a.w.show():a.w.hide());
for(var d in a.g)d!=b&&g.L(a.g[d].element,"ytp-ce-element-shadow-show",c)},u0=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||o0(a))c&&c();else{b=toa(a,b);var e=0,f=!1,k=new g.I(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Up(b[a],d)}},v0=function(a,b,c){u0(a,b.clickUrls,c);
(a=g.MA())&&b.OC&&g.FA(a,b.visualElement)},toa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(uoa(b[e],c));return d},uoa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},w0=function(a){return g.La(a)&&a.length?a[0]:a},x0=function(a){return g.Da(a)?a:""},y0=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},woa=function(a){var b=voa;
if(null==a)return null;if(g.Ma(a)){var c=[];(0,g.z)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},xoa=function(a){this.externalId=a},z0=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},A0=function(a){if(!a)return null;
var b=g.Bc(x0(a.value));b=g.zc(b);if(!b)return null;var c=y0(a.target,yoa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new z0(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},B0=function(a){return a.value?a.value:null},C0=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},voa=function(a){if(!a)return null;
var b=y0(a.type,zoa),c=y0(a.trigger,Aoa),d=w0(a.url);d=A0(d?d:null);a=w0(a.subscribeData);var e=a?a:null;e?(a=x0(e.external_user_id),e=x0(e.subscription_token),a=a&&e?new xoa(a):null):a=null;return b?new C0(b,c,d,a):null},D0=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.g=d||[];this.data=e},E0=function(a){return(a=Boa(a,function(b){return"openUrl"==b.type&&null!=b.url}))?a.url:null},Boa=function(a,b){return g.Ya(a.g,b,void 0)},F0=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Coa=function(a,b){this.merchant=a;
this.price=b},Doa=function(a){this.g=a},Eoa=function(a,b,c){b&&(c?G0(a,(0,g.ee)(b,g.Ra(function(d,e){return g.Xm(e,d)},c))):G0(a,b))},G0=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.z)(b||[],function(m){e++;
g.Up(m,l)});
d&&(e++,0!=d&&a.g.sendVideoStatsEngageEvent(d,l))},Foa=function(a,b,c,d,e,f,k){this.g=a;
this.l=b;this.Xa=c;this.videoData=d;this.logger=e;this.Z=f;this.i=k},H0=function(a,b){this.g=a;
this.l=b},Hoa=function(a,b){var c=[];
(0,g.z)(b.choices,function(k){c.push(Goa(b,k))},a);
var d={A:"ul",K:{role:"radiogroup"},H:c},e={};b.nh&&(e["aria-label"]=g.LL("$POLL_TITLE - \u6295\u7968\u3059\u308b\u306b\u306f\u30ed\u30b0\u30a4\u30f3\u3057\u3066\u304f\u3060\u3055\u3044\u3002",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{A:"div",F:"iv-card-content",H:[I0("h2",e,b.title),{A:"form",H:[{A:"fieldset",H:[d]}]}]}];b.nh&&(f.push("iv-card-unavailable"),d.push({A:"div",U:["iv-card-sign-in"],H:[{A:"h2",T:"\u30a2\u30f3\u30b1\u30fc\u30c8\u306b\u53c2\u52a0\u3059\u308b\u306b\u306f"},
{A:"a",U:["iv-card-sign-in-button","iv-button"],K:{href:B0(b.nh)},H:[{A:"span",U:["iv-button-content"],T:"\u30ed\u30b0\u30a4\u30f3"}]}]}));f=new g.T({A:"div",U:f,H:d});d=f.element;J0(b,d);ooa(a.g.g,d,g.Ra(a.o,b),a);(0,g.z)(g.Dd("iv-card-poll-choice-input",d),function(k){this.g.g.ea(k,"focus",g.Ra(this.i,!0));this.g.g.ea(k,"blur",g.Ra(this.i,!1))},a);
b.nh&&(d=g.Ed("iv-card-sign-in-button",d),a.l(d,b.nh,b.id,b.Db,b.lc.click,5));return f},N0=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.LL?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.RC&&b.Et?{A:"span",U:d,K:e,T:b.Et}:"";c={A:"div",U:["iv-card",c],H:[{A:"a",F:"iv-click-target",K:{href:B0(b.url)},H:[K0(b.ph,d?{A:"div",F:"iv-card-image-text",H:[d,b.priceText]}:""),{A:"div",F:"iv-card-content",H:[{A:"h2",F:"iv-card-primary-link",T:b.title},L0(a,b)]}]}]};c=new g.T(c);M0(a,g.Dd("iv-click-target",c.element),b,b.url);return c},O0=function(a){return a.customMessage?
I0("div","iv-card-message",a.customMessage):""},K0=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{A:"div",F:"iv-card-image",K:{style:c},H:d}},L0=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.z)(b.metaInfo,function(d){c.push(I0("li","",d))},a);
return{A:"ul",F:"iv-card-meta-info",H:c}},Goa=function(a,b){return{A:"li",
F:F0(a,b.index),H:[{A:"label",H:[{A:"input",F:"iv-card-poll-choice-input",K:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{A:"span",F:"iv-card-poll-choice-text",H:[{A:"span",F:"iv-card-poll-choice-percent"},I0("span",void 0,b.desc)]}]},{A:"div",F:"iv-card-poll-result",H:[{A:"div",F:"iv-card-poll-result-bar"}]}]}},I0=function(a,b,c){b?g.Da(b)?b={"class":b}:g.La(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.qn(c);return{A:a,K:b,T:c}},P0=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.jl&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.jl+");");c.dir=g.qn(a.customMessage);var d=[{A:"span",T:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({A:"span",F:"iv-card-link-icon"}));return{A:"div",U:b,K:c,H:d}},J0=function(a,b){var c=0;
(0,g.z)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Ed(F0(a,e.index),b);e=e.count/c;null==a.ee&&(e=0);g.L(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.ee==d);f.getElementsByTagName("input")[0].checked=a.ee==d;var k=Math.floor(100*e).toFixed(0),l=g.Ed("iv-card-poll-choice-percent",f);g.Zd(l,g.LL("$PERCENT%",{PERCENT:k}));f=g.Ed("iv-card-poll-result-bar",f);g.Xf(f,"transform","scaleX("+e.toFixed(2)+")")}g.L(b,"iv-card-poll-voted",null!=a.ee);g.L(b,"iv-card-poll-expanded",
null!=a.ee&&1<a.choices.length)},M0=function(a,b,c,d){d&&(0,g.z)(b,function(e){this.l(e,d,c.id,c.Db,c.lc.click,5)},a)},Q0=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Ioa=function(a,b){return b?b:Q0(a)?"current":"new"},R0=function(a,b){g.F.call(this);
this.g=a;this.context=b;this.hs=!1},Joa=function(a,b,c,d,e){var f=B0(b);
if(f){var k=Ioa(f,b.target),l=(0,g.x)(function(){b.g&&this.context.Z.pauseVideo();var m=this.context.videoData.Wb||!1,n=g.fp(f||"");m&&n&&(n.v||n.list)?g.oS(this.context.Z.app,n.v,c,n.list,!1,void 0):g.RL(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);G0(a.context.logger,d,l,e);Q0(f)||(a=g.MA(),d=c.itct,a&&d&&g.FA(a,g.qA(d)))}},S0=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},T0=function(a,b,c){return{vv:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
rz:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Bn:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},W0=function(a,b,c){R0.call(this,b,c);
var d=this;this.l=a;this.W=this.wa=this.w=this.va=!1;this.X=null;this.aa=new g.I(g.Ia,c.Xa.Mc?4E3:3E3);g.H(this,this.aa);this.ka=new g.I(g.Ia);g.H(this,this.ka);this.D=new H0(c,(0,g.x)(this.si,this),(0,g.x)(this.lm,this));this.P=new g.T({A:"div",F:"iv-drawer",K:{id:"iv-drawer"},H:[{A:"div",F:"iv-drawer-header",K:{"aria-role":"heading"},H:[{A:"span",F:"iv-drawer-header-text"},{A:"button",U:["iv-drawer-close-button","ytp-button"],K:{"aria-label":"\u30ab\u30fc\u30c9\u3092\u9589\u3058\u308b",tabindex:"0"}}]},
{A:"div",F:"iv-drawer-content"}]});g.H(this,this.P);this.B=this.P.element;this.ma=new g.eL(this.P,330);g.H(this,this.ma);this.ua=g.Ed("iv-drawer-header-text",this.B);this.u=g.Ed("iv-drawer-content",this.B);this.o=[];this.la=this.M=this.C=this.da=this.i=null;this.S=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.wa&&U0(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.wa=d.w)&&V0(d)});
this.R=this.G=this.Y=null;this.I=0},Koa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){U0(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){V0(a)});
var c=b.data.headerText;g.Zd(a.ua,c);a.M&&a.M.setAttribute("title",c);a.Y=g.qA(b.data.trackingParams);a.R=g.qA(b.data.closeTrackingParams);a.G=g.qA(b.data.iconTrackingParams)},Loa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"simple",teaserText:g.BB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Db:X0(a,c,b),sponsored:!1,lc:T0(d,e,d.command),Fd:d.trackingParams?g.qA(d.trackingParams):null,Cd:e.trackingParams?
g.qA(e.trackingParams):null,Qc:f&&f.trackingParams?g.qA(f.trackingParams):null,imageUrl:d.image.thumbnails[0].url,displayDomain:d.displayDomain?g.BB(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,jl:null,title:d.title?g.BB(d.title):"",customMessage:d.callToAction?g.BB(d.callToAction):"",url:d.command.urlEndpoint.url?A0({pause_on_navigation:!a.context.videoData.na,target:"new",value:d.command.urlEndpoint.url}):null};Y0(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"collaborator",teaserText:g.BB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Db:X0(a,c,b),sponsored:!1,lc:T0(d,e,d.endpoint),Fd:d.trackingParams?g.qA(d.trackingParams):null,Cd:e.trackingParams?g.qA(e.trackingParams):null,Qc:f&&f.trackingParams?g.qA(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.BB(d.customText):null,vy:d.channelAvatar.thumbnails[0].url,title:d.channelName?g.BB(d.channelName):"",metaInfo:[d.subscriberCountText?g.BB(d.subscriberCountText):""],url:A0({pause_on_navigation:!a.context.videoData.na,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};Y0(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"playlist",teaserText:g.BB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Db:X0(a,c,b),sponsored:!1,lc:T0(d,e,d.action),Fd:d.trackingParams?g.qA(d.trackingParams):null,Cd:e.trackingParams?g.qA(e.trackingParams):null,Qc:f&&f.trackingParams?g.qA(f.trackingParams):
null,ph:d.playlistThumbnail.thumbnails[0].url,customMessage:d.customMessage?g.BB(d.customMessage):null,playlistVideoCount:g.BB(d.playlistVideoCount),title:d.playlistTitle?g.BB(d.playlistTitle):"",metaInfo:[d.channelName?g.BB(d.channelName):"",d.videoCountText?g.BB(d.videoCountText):""],url:A0({pause_on_navigation:!a.context.videoData.na,target:"new",value:S0(d.action)})};Y0(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"video",teaserText:g.BB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Db:X0(a,c,b),sponsored:!1,lc:T0(d,e,d.action),Fd:d.trackingParams?g.qA(d.trackingParams):null,Cd:e.trackingParams?g.qA(e.trackingParams):null,Qc:f&&f.trackingParams?g.qA(f.trackingParams):null,ph:d.videoThumbnail.thumbnails[0].url,
videoDuration:d.lengthString?g.BB(d.lengthString):null,customMessage:d.customMessage?g.BB(d.customMessage):null,title:d.videoTitle?g.BB(d.videoTitle):"",metaInfo:[d.channelName?g.BB(d.channelName):"",d.viewCountText?g.BB(d.viewCountText):""],isLiveNow:!!d.badge,url:A0({pause_on_navigation:!a.context.videoData.na,target:"new",value:S0(d.action)})};Y0(a,c)}a.I++},X0=function(a,b,c){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:c.trackingParams}},$0=function(a,b){var c=Moa(a,b);
c&&(c==a.i&&(a.i=null),a.l.removeCueRange(c.card.id),g.Ud(c.Jo),g.eb(a.o,c),a.ll(),Z0(a))},U0=function(a,b,c){if(!a.w){a.ma.show();
a.da=new g.I(function(){g.K(a.context.Z.getRootNode(),"ytp-iv-drawer-open")},0);
a.da.start();a.X=g.Yq(a.u,"mousewheel",(0,g.x)(a.TD,a));a.w=!0;var d=g.MA();d&&a.Y&&a.R&&Y_(d,[a.Y,a.R]);var e={TRIGGER_TYPE:b};(0,g.z)(a.o,function(f){f.Vv||(f.Vv=!0,Eoa(a.context.logger,f.card.lc.vv,e));d&&Y_(d,[f.card.Fd])});
X_(a.l);c&&(a.C=new g.I(function(){a.ca=a.M;a.la.focus()},330),a.C.start())}},V0=function(a){a.w&&(a.ma.hide(),g.Zq(a.X),a.X=null,g.kn(a.context.Z.getRootNode(),"ytp-iv-drawer-open"),a.w=!1,X_(a.l),a.C&&a.C.stop(),a.C=new g.I(function(){a.ca&&(a.ca.focus(),a.ca=null)},330),a.C.start())},Noa=function(a){var b=g.Ed("iv-drawer-close-button",a.B);
a.context.g.ea(b,"click",a.eB,a);a.context.g.ea(a.u,"touchend",function(){a.aa.start()});
a.context.g.ea(a.u,"scroll",a.rB,a);a.context.i.subscribe("onHideControls",function(){a.W=!0});
a.context.i.subscribe("onShowControls",function(){a.W=!1});
a.context.i.subscribe("onVideoAreaChange",function(){a.W=g.hn(a.l.getRootNode(),"ytp-autohide")});
a.S.push(g.Io("iv-button-shown",a.bD,a));a.S.push(g.Io("iv-button-hidden",a.aD,a));a.S.push(g.Io("iv-teaser-shown",a.eD,a));a.S.push(g.Io("iv-teaser-hidden",a.dD,a));a.S.push(g.Io("iv-teaser-clicked",a.cD,a))},Y0=function(a,b){a.va||(g.jn(a.g,["html5-stop-propagation",
"iv-drawer-manager"]),g.tK(a.l,a.B,5),Noa(a),a.M=g.Ed("ytp-cards-button",a.l.getRootNode()),a.la=g.Ed("iv-drawer-close-button",a.B),a.va=!0);$0(a,b.id);var c=Ooa(a,b);if(c){var d={card:b,Jo:c.element,Vv:!1},e=Poa(a,d);g.lb(a.o,e,0,d);c.g(a.u,e);a.ll();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Ra(a.hL,d)):(c=1E3*a.context.Z.getCurrentTime(),5E3>c&&c>b.startMs&&a.bz(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Ra(a.bz,d)),Z0(a))}},Ooa=function(a,b){switch(b.type){case "simple":var c=
a.D;
var d=b.displayDomain?{A:"div",F:"iv-card-image-text",T:b.displayDomain}:"";var e=P0(b);d={A:"div",U:["iv-card"],H:[{A:"a",F:"iv-click-target",K:{href:B0(b.url)},H:[K0(b.imageUrl,d),{A:"div",F:"iv-card-content",H:[I0("h2",void 0,b.title),e]}]}]};d=new g.T(d);M0(c,g.Dd("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.D,d={A:"div",U:["iv-card","iv-card-channel"],H:[{A:"a",U:["iv-click-target"],K:{href:B0(b.url),"data-ytid":b.channelId},H:[K0(b.vy),{A:"div",F:"iv-card-content",
H:[O0(b),{A:"h2",F:"iv-card-primary-link",T:b.title},L0(c,b)]}]}]},d=new g.T(d),M0(c,g.Dd("iv-click-target",d.element),b,b.url),d;case "episode":return N0(a.D,b,"iv-card-episode");case "movie":return N0(a.D,b,"iv-card-movie");case "playlist":return c=a.D,d={A:"div",U:["iv-card","iv-card-playlist"],H:[{A:"a",F:"iv-click-target",K:{href:B0(b.url)},H:[K0(b.ph,{A:"div",F:"iv-card-image-overlay",H:[{A:"span",F:"iv-card-playlist-video-count",T:b.playlistVideoCount}]}),{A:"div",F:"iv-card-content",H:[O0(b),
I0("h2","iv-card-primary-link",b.title),L0(c,b)]}]}]},d=new g.T(d),M0(c,g.Dd("iv-click-target",d.element),b,b.url),d;case "poll":return Hoa(a.D,b);case "productListing":c=a.D;var f=!g.bb(b.offers);d=["iv-card"];e="";var k=P0(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({A:"div",F:"iv-card-offer-price",T:f.price}),f.merchant&&k.push({A:"div",F:"iv-card-offer-merchant",T:f.merchant}),k={A:"div",H:k});d={A:"div",U:d,K:{tabindex:"0"},H:[{A:"a",U:["iv-card-image",
"iv-click-target"],K:{style:"background-image: url("+b.imageUrl+");",href:B0(b.url),"aria-hidden":"true",tabindex:"-1"}},{A:"div",F:"iv-card-content",H:[b.sponsored?{A:"div",F:"iv-card-sponsored",H:["\u30b9\u30dd\u30f3\u30b5\u30fc\u63d0\u4f9b",{A:"div",F:"iv-ad-info-container",H:[{A:"div",F:"iv-ad-info",T:"{{adInfo}}"},{A:"div",F:"iv-ad-info-icon-container",H:[{A:"div",F:"iv-ad-info-icon"},{A:"div",F:"iv-ad-info-callout"}]}]}]}:"",{A:"a",F:"iv-click-target",K:{href:B0(b.url)},H:[I0("h2",e,b.title),
k]}]}]};d=new g.T(d);e=g.Pd("span");g.Zd(e,"\u3053\u306e\u52d5\u753b\u306b\u95a2\u9023\u3057\u3066\u3044\u308b\u3068\u601d\u308f\u308c\u308b\u5546\u54c1\u3092\u8868\u793a\u3057\u3066\u3044\u307e\u3059\u3002Google \u306f\u8ca9\u58f2\u8005\u304b\u3089\u652f\u6255\u3044\u3092\u53d7\u3051\u3066\u3044\u308b\u3053\u3068\u304c\u3042\u308a\u307e\u3059\u3002");d.ib(e,"adInfo");M0(c,g.Dd("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.D,d=b.isLiveNow?{A:"span",U:["yt-badge","yt-badge-live"],
T:"\u30e9\u30a4\u30d6\u914d\u4fe1\u4e2d"}:"",d={A:"div",U:["iv-card","iv-card-video"],H:[{A:"a",F:"iv-click-target",K:{href:B0(b.url)},H:[K0(b.ph,b.videoDuration?{A:"span",F:"iv-card-video-duration",T:b.videoDuration}:""),{A:"div",F:"iv-card-content",H:[O0(b),I0("h2","iv-card-primary-link",b.title),L0(c,b),d]}]}]},d=new g.T(d),M0(c,g.Dd("iv-click-target",d.element),b,b.url),d}return null},Poa=function(a,b){if(0==a.o.length)return 0;
var c=g.Za(a.o,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},Qoa=function(a){return a.i?"productListing"==a.i.card.type:(0,g.Xg)(a.o,function(b){return"productListing"==b.card.type})},Z0=function(a){g.L(a.l.getRootNode(),"ytp-cards-shopping-active",Qoa(a))},a1=function(a,b){if(a.P.Da()){var c=new e0([0,
a.u.scrollTop],[0,b.Jo.offsetTop],600,moa);a.context.l.ea(c,"animate",function(d){a.u.scrollTop=d.y});
a.context.l.ea(c,"finish",function(d){a.u.scrollTop=d.y});
c.play()}else g.ru(a.P,!0),a.u.scrollTop=b.Jo.offsetTop,g.ru(a.P,!1)},b1=function(a){return a.i&&a.i.card?a.i.card:a.o[0]&&a.o[0].card?a.o[0].card:null},Moa=function(a,b){return g.Ya(a.o,function(c){return c.card.id==b})},c1=function(a,b,c){R0.call(this,a,b);
this.annotation=c;this.isActive=!1},Roa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},d1=function(a,b,c){c1.call(this,a,b,c);
this.l=null;this.C=!1;this.o=null;this.u=!1;this.i=this.B=this.w=null},e1=function(a,b,c){c1.call(this,a,b,c);
this.G=this.w=this.I=!1;this.C=5E3;this.u=null;this.D=g.Od("DIV","iv-promo-contents");this.l=this.o=this.i=null;this.B=new g.I(function(){this.i.setAttribute("aria-hidden",!0);g.rg(this.o,!1);g.rg(this.l,!0)},700,this);
g.H(this,this.B)},Soa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.C=b.collapse_delay_ms||a.C;var d=["iv-promo","iv-promo-inactive"];a.g.setAttribute("aria-hidden",!0);a.g.setAttribute("aria-label","\u30d7\u30ed\u30e2\u30fc\u30b7\u30e7\u30f3");a.g.tabIndex=0;var e=E0(a.annotation),f=b.image_url;if(f){var k=g.Od("DIV",["iv-promo-img","iv-click-target"]);f=g.Od("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Od("SPAN",
"iv-promo-video-duration",b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.Od("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.si(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.Od("A","iv-promo-txt"),g.Sc(f,B0(e)),a.i=f):a.i=g.Od("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Od("P",null,g.Od("STRONG",null,b.text_line_1));var m=g.Od("P",null,g.Od("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.P(a.context.Xa.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Od("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Od("BUTTON",["iv-button","iv-promo-button"],g.Od("SPAN","iv-button-content",f));var q=g.Od("DIV","iv-promo-button-container");q.appendChild(f);e&&a.si(a.g,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.i,"iv-click-target");e&&a.si(a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.Od("P",null,
g.Od("SPAN",null,b.text_line_1)),m=g.Od("P",null,g.Od("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Od("SPAN",["yt-badge","iv-promo-badge-live"],"\u30e9\u30a4\u30d6\u914d\u4fe1\u4e2d")),g.K(a.i,"iv-click-target"),e&&a.si(a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.D.appendChild(a.i);q&&a.D.appendChild(q);c=g.Od("DIV","iv-promo-actions");a.l=g.Od("BUTTON",["iv-promo-expand","ytp-button"]);a.l.title="\u62e1\u5927";a.context.g.ea(a.l,
"click",g.Ra(a.zp,5E3),a);c.appendChild(a.l);g.rg(a.l,!1);a.context.g.ea(a.g,"mouseover",a.jC,a);a.context.g.ea(a.g,"mouseout",a.iC,a);a.context.g.ea(a.g,"touchend",g.Ra(a.zp,5E3),a);a.o=g.Od("BUTTON",["iv-promo-close","ytp-button"]);a.o.title="\u9589\u3058\u308b";a.context.g.ea(a.o,"click","cta"==a.annotation.style&&b.text_line_3?a.bC:a.aC,a);c.appendChild(a.o);g.jn(a.g,d);k&&(a.g.appendChild(k),n&&k.appendChild(n));a.g.appendChild(a.D);a.g.appendChild(c)},f1=function(a){a.w||a.G||a.u||(g.K(a.g,
"iv-promo-collapsed"),a.w=!0,a.B.start())},g1=function(a){a.B.stop();
a.w&&(g.ln(a.g,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.w=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.rg(a.l,!1),g.rg(a.o,!0))},i1=function(a,b){a.u||(a.u=g.fl(function(){h1(this);
f1(this)},b,a))},h1=function(a){a.u&&(g.u.clearTimeout(a.u),a.u=null)},j1=function(a){g.QO.call(this,a);
this.G=!1;this.D=0;this.B={};this.P=new Doa(a);this.u=new g.Is(this);g.H(this,this.u);this.w=this.l=null;this.u.J(this.player,"onVideoAreaChange",(0,g.x)(this.N,this,"onVideoAreaChange"));this.u.J(this.player,"onHideControls",(0,g.x)(this.N,this,"onHideControls"));this.u.J(this.player,"onShowControls",(0,g.x)(this.N,this,"onShowControls"));this.u.J(this.player,"resize",(0,g.x)(this.N,this,"resize"));this.u.J(this.player,"presentingplayerstatechange",(0,g.x)(this.N,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.SI,this);this.subscribe("resize",this.Zm,this);this.player.L().D.subscribe("vast_info_card_add",this.iy,this);this.M=new g.Is(this);g.H(this,this.M);this.R=g.Od("DIV","video-custom-annotations");this.i=new g.T({A:"div",U:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.i);g.tK(this.player,this.i.element,4);this.i.hide();this.o=new g.T({A:"div",U:["ytp-iv-video-content"]});g.H(this,this.o);g.Rd(this.o.element,g.Od("DIV","video-annotations",
this.R));this.C=this.g=null;this.I=[];Toa(this)&&this.load();var b=g.Pd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.zi(this,function(){g.Ud(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},k1=function(){var a=g.Od("DIV",["annotation",
"annotation-type-custom"]);g.rg(a,!1);return a},l1=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},Toa=function(a){var b=a.player.L();
a=a.player.getVideoData();return 1==(b.Jf||a.Jf)&&!a.Vz||null!==b.D.get(a.videoId)},m1=function(a,b,c){a.G=!0;
a.w=g.zp(b,c)},n1=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Oa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(n1(a,e))}return c},o1=function(a,b,c){return!(a.loaded&&a.D==b&&a.player.getVideoData().videoId==
c)},Uoa=function(a){var b=a.player.getVideoData();
if(b.Ed){var c=a.player.L().D.get(b.videoId);if(c){var d={format:"XML",pd:{},method:"POST",withCredentials:!0};d.Wc=(0,g.x)(function(e,f,k){o1(this,e,f)||(e=g.tp(k)&&k.responseXML?k.responseXML:null)&&p1(this,e)},a,a.D,b.videoId);
g.Wo()&&(d.Wc=q1(a,d.Wc));d.rb={ic_only:"1"};r1(d,c);a.G=!0;g.zp(b.Ed,d)}}},r1=function(a,b){a.method="POST";
a.rb=a.rb||{};b.ql&&(a.rb.ic_coll=b.ql);b.rl&&(a.rb.ic_xml=b.rl);b.Sr&&(a.rb.ic_track=b.Sr)},t1=function(a){var b=new g.T({A:"div"});
g.rg(b.element,!1);var c=new W0(a.player,b.element,s1(a));g.H(c,b);b.g(a.i.element);c.mk();return c},s1=function(a){if(!a.C){var b=new j0(a);
g.H(a,b);var c=new g.$Y(a);g.H(a,c);a.C=new Foa(b,c,a.player.L(),a.player.getVideoData(),a.P,a.player,a.Qb)}return a.C},p1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.MA();if(e){var f=g.LA();f&&g.DA(e,f,[g.qA(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=n1(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n=g.Da(l)&&null!=m&&null!=l&&l.match(m)?l:"";var q=y0(k.type,Voa),t=y0(k.style,Woa),v=x0(k.data),y=0!=v.length?JSON.parse(v):{},B=woa(k.action);f=n&&q?new D0(n,q,t,B,y):null}else f=null}catch(M){}if(f){a:{switch(f.type){case "branding":case "promotion":k=!0;break a}k=!1}if(k){k=
a;m=f;var C=k1(),G=null;switch(m.type){case "branding":if(k.player.L().Ac)break;k.i.element.appendChild(C);G=new d1(C,s1(k),m);break;case "promotion":g.tK(k.player,C,4),G=new e1(C,s1(k),m)}G&&G.mk();if(k=G)g.H(a,k),a.B[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.g||(a.g=t1(a),g.H(a,a.g));if("card"==f.type){if(c=a.g,G=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={vv:k.impression,click:k.click,close:k.close,rz:k.teaser_impression,Bn:k.teaser_click},m=f.data.tracking_params||{},
C=null,G){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Db:f.data.session_data||{},sponsored:f.data.sponsored||!1,lc:k,Fd:m.card?g.qA(m.card):null,Cd:m.teaser?g.qA(m.teaser):null,Qc:m.icon?g.qA(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,vy:f.data.image_url,title:f.data.title,
metaInfo:f.data.meta_info,url:A0({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};Y0(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Db:f.data.session_data||{},sponsored:f.data.sponsored||!1,lc:k,Fd:m.card?g.qA(m.card):null,Cd:m.teaser?g.qA(m.teaser):null,Qc:m.icon?g.qA(m.icon):
null,ph:f.data.image_url,Et:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,RC:!!f.data.is_paygated,LL:!!f.data.user_has_entitlement,url:A0({target:f.data.target||"new",value:f.data.url})};Y0(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Db:f.data.session_data||{},sponsored:f.data.sponsored||
!1,lc:k,Fd:m.card?g.qA(m.card):null,Cd:m.teaser?g.qA(m.teaser):null,Qc:m.icon?g.qA(m.icon):null,ph:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:A0({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};Y0(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,
startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Db:f.data.session_data||{},sponsored:f.data.sponsored||!1,lc:k,Fd:m.card?g.qA(m.card):null,Cd:m.teaser?g.qA(m.teaser):null,Qc:m.icon?g.qA(m.icon):null,title:f.data.title,choices:f.data.choices,ee:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,nh:f.data.signin_url?A0({target:"current",value:f.data.signin_url}):null,VL:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};Y0(c,f);break;case "productListing":f.data.signin_url&&(C=A0({target:"current",
value:f.data.signin_url}));G=[];for(var J=f.data.offers||[],E=0;E<J.length;E++)G.push(new Coa(g.ad(J[E].merchant),g.ad(J[E].price)));f={yP:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Db:f.data.session_data||{},sponsored:f.data.sponsored||!1,lc:k,Fd:m.card?g.qA(m.card):null,Cd:m.teaser?g.qA(m.teaser):null,Qc:m.icon?g.qA(m.icon):null,imageUrl:f.data.image_url,
displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,jl:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:A0({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),nh:C,HP:f.data.signin_title?f.data.signin_title:null,GP:f.data.signin_message?f.data.signin_message:null,offers:G};Y0(c,f);break;case "simple":f={id:f.id,timestamp:f.data.timestamp||
0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Db:f.data.session_data||{},sponsored:f.data.sponsored||!1,lc:k,Fd:m.card?g.qA(m.card):null,Cd:m.teaser?g.qA(m.teaser):null,Qc:m.icon?g.qA(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,jl:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,
customMessage:f.data.custom_message?f.data.custom_message:null,url:A0({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};Y0(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Db:f.data.session_data||{},sponsored:f.data.sponsored||!1,lc:k,Fd:m.card?g.qA(m.card):null,Cd:m.teaser?g.qA(m.teaser):
null,Qc:m.icon?g.qA(m.icon):null,ph:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:A0({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},Y0(c,f)}}else Koa(a.g,f);c=!0}}}c&&(X_(a.player),a.Zm())},Xoa=function(a,b){var c=!1;
a.g||(a.g=t1(a),g.H(a,a.g));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())Loa(a.g,e.value.cardRenderer),c=!0;c&&(c=a.g,d=b.headerText?g.BB(b.headerText):"",g.Zd(c.ua,d),c.M&&c.M.setAttribute("title",d),c.Y=b.trackingParams?g.qA(b.trackingParams):null,c.R=b.closeButton.infoCardIconRenderer.trackingParams?g.qA(b.closeButton.infoCardIconRenderer.trackingParams):null,c.G=b.icon.infoCardIconRenderer.trackingParams?g.qA(b.icon.infoCardIconRenderer.trackingParams):null,X_(a.player),a.Zm())},Yoa=
function(a,b,c,d){if(!a.player.L().Ac){var e=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&e.push(new C0("openUrl","click",new z0("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var f=b.watermark.thumbnails[0];b=new D0("branding","branding","branding",e,{channel_id:"",channel_name:"",end_ms:b.endTimeMs,image_height:f.height,image_type:1,image_url:f.url,image_width:f.width,is_mobile:!1,num_subscribers:"",session_data:{annotation_id:"branding",ei:d,feature:"iv",
itct:b.trackingParams,src_vid:c},IP:null,JP:b.startTimeMs});c=k1();a.i.element.appendChild(c);b=new d1(c,s1(a),b);b.mk();g.H(b,b);a.B.branding=b}},q1=function(a,b){return(0,g.x)(function(){if(!this.fa()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Ra.apply(window,c);this.I.push(g.Uo(b))}},a)},$_={},a0=null;g.Ta(e0,g.mn);g.h=e0.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.l;else if(1==this.g)return!1;b0(this);this.startTime=a=(0,g.A)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.u();this.Ud("play");-1==this.g&&this.Ud("resume");this.g=1;var b=g.Qa(this);b in $_||($_[b]=this);c0();d0(this,a);return!0};
g.h.stop=function(a){b0(this);this.g=0;a&&(this.progress=1);f0(this,this.progress);this.Ud("stop");this.o()};
g.h.pause=function(){1==this.g&&(b0(this),this.g=-1,this.Ud("pause"))};
g.h.V=function(){0==this.g||this.stop(!1);this.Ud("destroy");e0.wb.V.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Vq=function(){this.Ud("animate")};
g.h.Ud=function(a){this.dispatchEvent(new g0(a,this))};
g.Ta(g0,g.Xj);g.Ta(h0,e0);h0.prototype.w=g.Ia;h0.prototype.Vq=function(){this.w();h0.wb.Vq.call(this)};
h0.prototype.o=function(){this.w();h0.wb.o.call(this)};
h0.prototype.u=function(){this.w();h0.wb.u.call(this)};
g.Ta(i0,h0);i0.prototype.w=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(j0,g.F);j0.prototype.ea=function(a,b,c,d){c=(0,g.x)(c,d||this.i);a=g.Yq(a,b,c);this.g.push(a);return a};
j0.prototype.Xp=function(a,b,c,d){c=(0,g.x)(c,d||this.i);a=g.hr(a,b,c);this.g.push(a);return a};
j0.prototype.Sa=function(a){g.Zq(a);g.eb(this.g,a)};
j0.prototype.V=function(){g.Zq(this.g);this.g.length=0;g.F.prototype.V.call(this)};g.r(m0,g.QO);g.h=m0.prototype;g.h.load=function(){g.QO.prototype.load.call(this);if(!o0(this)){var a=g.qC(this.player.getVideoData());if(a)a=l0(a,n0(this)),p0(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Wc:(0,g.x)(this.DH,this,a),pd:{v:a},withCredentials:!0};this.I&&(a.pd.ptype="embedded");var c=this.player.getVideoData().lu;c&&(a.rb={ad_tracking:c});if(b=g.pC(b))if(b=g.Bc(b),b=g.zc(b))this.o=g.zp(b,a)}}};
g.h.unload=function(){p0(this,null);this.o&&(this.o.abort(),this.o=null);g.QO.prototype.unload.call(this)};
g.h.sc=function(a,b){if(!o0(this))return null;if("loadCustomEndscreenRenderer"==a){var c=l0(b,"new");p0(this,c);return!0}return null};
g.h.getOptions=function(){return o0(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.DH=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=l0(c,n0(this)))}p0(this,c)};
g.h.Na=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<u1.length;f++){var k=Math.abs(b.width-u1[f]);if(-1==e||d>=k)e=f,d=k}d=v1[e];this.l&&g.Xf(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.B[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.pg(e.element,Math.round(k.width*a.width),f);g.eg(e.element,m,n);g.ln(e.element,Zoa);m=k.left+k.width/2;k=k.top+l/2;g.K(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.ln(e.element,v1);g.K(e.element,d);(e=g.Cd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Xf(e,"height",f+"px")}}}}};
g.h.yD=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.D=!1,this.i.skip&&1==this.player.getPlayerState()?(g.SR(this.player.app,!0),this.player.seekTo(Infinity),this.D=!0):(u0(this,this.i.impressionUrls),(a=g.MA())&&this.i.visualElement&&g.EA(a,this.i.visualElement));else if(!this.D){a=a.getId().substring(15);var b=this.g[a],c=this.B[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.K(b,"ytp-ce-shown");u0(this,c.impressionUrls);
(b=g.MA())&&g.EA(b,c.visualElement);this.player.L().ub&&this.player.ha("endscreenelementshown",a)}};
g.h.zD=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.D){a=a.getId().substring(15);var b=this.g[a];g.kn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.kn(b,"ytp-ce-shown");this.player.L().ub&&this.player.ha("endscreenelementhidden",a)}};
g.h.vK=function(a){var b=this;a.target===window&&(new g.I(function(){for(var c in b.g)g.ln(b.g[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.Hx=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.hn(c,"ytp-ce-element");){g.hn(c,"subscribe-label")&&v0(this,a);if(g.hn(c,"ytp-ce-channel-subscribe"))return;c=g.Xd(c)}if(!c||g.hn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.ar(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.vL?(v0(this,a),this.az(),this.player.pauseVideo(),c=g.Bc(r0(this,a.targetUrl)),c=g.zc(c),g.RL(c,void 0,a.Db)):(c=this.player.getVideoData().Wb,
c=(0,g.x)(this.oL,this,c,r0(this,a.targetUrl),a.Db),c=(0,g.x)(this.az,this,c),v0(this,a,c))}}};
g.h.oL=function(a,b,c){var d=g.fp(b);a&&d&&(d.v||d.list)?g.oS(this.player.app,d.v,c,d.list,!1,void 0):g.QL(b,c)};
g.h.lq=function(a,b){g.hn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.K(a.element,"ytp-ce-element-hover"):this.player.L().g?(new g.I(function(){g.K(a.element,"ytp-ce-element-hover")},200)).start():g.K(a.element,"ytp-ce-element-hover"),u0(this,b.FC),t0(this,b.id,!0))};
g.h.ar=function(a,b){g.kn(a.element,"ytp-ce-element-hover");g.kn(a.element,"ytp-ce-force-expand");t0(this,b.id,!1)};
g.h.az=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var u1=[346,426,470,506,570,640,853,1280,1920],v1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Zoa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var yoa={YM:"current",iO:"new"};var zoa={CLOSE:"close",lO:"openUrl",IA:"subscribe"},Aoa={SM:"click",CLOSE:"close",FN:"hidden",IO:"rollOut",JO:"rollOver",MO:"shown"};var Woa={wM:"anchored",lA:"branding",CHANNEL:"channel",XM:"cta",HN:"highlightText",VN:"label",PLAYLIST:"playlist",vO:"popup",QO:"speech",IA:"subscribe",aP:"title",VIDEO:"video",kP:"website"},Voa={lA:"branding",IM:"card",eN:"drawer",GN:"highlight",cO:"marker",AO:"promotion",TEXT:"text",mP:"widget"};H0.prototype.i=function(a,b){var c=g.de(b.target,"label");c&&g.L(c,"iv-card-poll-choice-focused",a)};
H0.prototype.o=function(a,b){var c=g.de(b.target,null,"iv-card-poll",void 0);if(c)if(a.nh)g.Ed("iv-card-sign-in-button",c).click();else{var d=parseInt(koa(b.target),10);if(null==a.ee)a.choices[d].count++,a.ee=d;else if(a.ee!=d){var e=a.choices[a.ee];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.ee=d}else e=a.choices[a.ee],e.count=Math.max(e.count-1,0),a.ee=null;J0(a,c);g.Dp(this.g.videoData.Ed,{pd:{action_poll_vote:1},rb:{poll_id:a.id,index:d,session_token:a.VL}});G0(this.g.logger,a.lc.click,
void 0,5);(c=g.MA())&&a.Fd&&g.FA(c,a.Fd)}};g.r(R0,g.F);g.h=R0.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.pD(a,b,{id:c});g.H(this,a);a.namespace="annotations_module";d&&W_(a).subscribe("onEnter",d,this);e&&W_(a).subscribe("onExit",e,this);g.pK(this.context.Z,[a])};
g.h.mk=function(){this.context.i.subscribe("resize",this.ll,this)};
g.h.si=function(a,b,c,d,e,f){this.context.g.ea(a,"click",g.Ra(this.lm,b,c,d,e||[],f||0),this);this.context.g.ea(a,"touchstart",g.Ra(function(){this.hs=!1}),this);
this.context.g.ea(a,"touchmove",g.Ra(function(){this.hs=!0}),this)};
g.h.lm=function(a,b,c,d,e,f){if(this.hs)return!1;f&&(f.stopPropagation(),f.preventDefault());Joa(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.Ud(this.g)};
g.h.ll=function(){};g.r(W0,R0);g.h=W0.prototype;g.h.isAvailable=function(){var a;if(a=!!this.o.length)(a=this.l.getRootNode())?(a=g.qg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.ll=function(){var a=this.isAvailable();g.rg(this.g,a);g.L(this.context.Z.getRootNode(),"ytp-iv-drawer-enabled",a);X_(this.l)};
g.h.destroy=function(){var a=g.hK(g.XJ(this.l));a&&a.kq(!1,void 0);this.l.getRootNode().removeChild(this.B);g.Jo(this.S);g.Zq(this.X);this.da&&this.da.dispose();this.C&&this.C.dispose();R0.prototype.destroy.call(this)};
g.h.TD=function(a){this.aa.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.u.scrollTop+=a};
g.h.bz=function(a){if(!g.hn(this.l.getRootNode(),"ytp-cards-teaser-shown")){if(this.i!=a){var b=g.MA(),c=this.i?this.i.card.Qc:this.G;b&&c&&Z_(b,[c]);this.i=a;Z0(this)}"none"!=this.g.style.display&&(2==this.context.Z.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.Z.getAdState():void 0):(b=isNaN(void 0)?this.context.Z.getPlayerState():void 0,b=1==b||0==b&&0===this.context.Z.getCurrentTime()),b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},
(c=g.hK(g.XJ(this.l)))&&c.kq(!0,b)));this.ka.isActive()||((!this.w||!this.aa.isActive()&&this.W)&&a1(this,a),this.ka.start(910+a.card.teaserDurationMs))}};
g.h.hL=function(a){this.w||(this.i=a,Z0(this),a1(this,a),U0(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.eB=function(){if(this.w){G0(this.context.logger,b1(this).lc.close);var a=g.MA();a&&this.R&&g.FA(a,this.R);V0(this)}};
g.h.rB=function(){g.L(this.B,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.h.bD=function(){var a=g.MA(),b=b1(this);b=b?b.Qc:this.G;a&&b&&Y_(a,[b])};
g.h.aD=function(){var a=g.MA(),b=b1(this);b=b?b.Qc:this.G;a&&b&&Z_(a,[b])};
g.h.eD=function(){var a=b1(this);G0(this.context.logger,a.lc.rz);var b=g.MA();b&&a&&Y_(b,[a.Cd,a.Qc])};
g.h.dD=function(){var a=g.MA(),b=b1(this);a&&b&&Z_(a,[b.Cd])};
g.h.cD=function(a){var b=b1(this),c=g.MA();this.i?a?(a=this.context.logger,G0(a,b.lc.Bn),a.g.sendVideoStatsEngageEvent(4,void 0),c&&b.Cd&&g.FA(c,b.Cd)):(a=this.context.logger,G0(a,b.lc.Bn),a.g.sendVideoStatsEngageEvent(4,void 0),c&&b.Qc&&g.FA(c,b.Qc)):(a=this.context.logger,G0(a,b.lc.Bn),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.G&&g.FA(c,this.G))};g.r(c1,R0);c1.prototype.mk=function(){R0.prototype.mk.call(this);Roa(this)};
c1.prototype.show=function(){R0.prototype.show.call(this);var a=g.MA(),b=this.annotation.data;a&&b&&(b=b.session_data)&&Y_(a,[g.qA(b.itct)])};
c1.prototype.hide=function(){R0.prototype.hide.call(this);var a=g.MA(),b=this.annotation.data;a&&b&&(b=b.session_data)&&Z_(a,[g.qA(b.itct)])};g.r(d1,c1);g.h=d1.prototype;g.h.pL=function(a,b,c,d){this.o.stop();if(!this.u){var e=g.qg(a);this.i||(g.og(a,e.width),g.og(b,e.width));g.Xf(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.Xf(c,"right","1px");this.u=!0;g.rg(a,!0);this.w=new g.I(function(){g.K(this.g,"iv-branding-active")},0,this);
this.w.start()}};
g.h.DC=function(a,b){g.kn(this.g,"iv-branding-active");this.B=new g.I((0,g.x)(function(){g.rg(a,!1);this.i||g.og(b,0)},this),250);
this.B.start();this.u=!1};
g.h.show=function(){if(!this.isActive){c1.prototype.show.call(this);if(!this.C){g.K(this.g,"iv-branding");var a=this.annotation.data;this.l=g.Od("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.rg(this.l,!1);var b=g.Od("DIV","branding-img-container",this.l);this.g.appendChild(b);(b=E0(this.annotation))&&this.si(this.l,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.Od("DIV","iv-branding-context-name");
g.Zd(c,a.channel_name);var d=g.Od("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.i=new g.$P(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.Z),this.i.g(d);b=g.Od("DIV","iv-branding-context-subscribe-caret");c=g.Od("DIV","branding-context-container-inner",b,c,d);g.rg(c,!1);d=g.Od("DIV","branding-context-container-outer",c);g.Xf(d,"right",
a.image_width+"px");this.g.appendChild(d);this.o=new g.I(g.Ra(this.DC,c,d),500,this);g.H(this,this.o);this.context.g.ea(this.g,"mouseover",(0,g.x)(this.pL,this,c,d,b,a.image_height));this.context.g.ea(this.g,"mouseout",(0,g.x)(this.o.start,this.o,void 0))}this.C=!0}g.rg(this.g,!0);this.isActive=!0;if(this.l){a=this.l;var e=void 0===e?0:e;b=g.ig(a);c=g.qg(a);b=(new g.Uf(b.x,b.y,c.width,c.height)).width;c=g.Fa(void 0)?void 0:b;g.eg(a,c);e=new i0(a,[c,a.offsetTop],[c-b-e,a.offsetTop],200,loa);g.H(this,
e);this.context.l.ea(e,"begin",g.Ra(g.rg,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(c1.prototype.hide.call(this),g.rg(this.g,!1),this.isActive=!1)};
g.h.destroy=function(){this.i&&(this.i.dispose(),this.i=null);c1.prototype.destroy.call(this)};g.r(e1,c1);g.h=e1.prototype;g.h.show=function(){this.isActive||(c1.prototype.show.call(this),this.I||(Soa(this),this.I=!0),g.rg(this.g,!0),g.fl(function(){g.kn(this.g,"iv-promo-inactive")},100,this),this.g.removeAttribute("aria-hidden"),this.isActive=!0,h1(this),g1(this),i1(this,this.C))};
g.h.hide=function(){this.isActive&&(g.K(this.g,"iv-promo-inactive"),this.isActive=!1,this.g.setAttribute("aria-hidden",!0))};
g.h.lm=function(a,b,c,d,e,f){return this.w?!1:c1.prototype.lm.call(this,a,b,c,d,e,f)};
g.h.zp=function(a,b){b.stopPropagation();g1(this);i1(this,a);this.i.focus()};
g.h.jC=function(a){this.G=!0;this.zp(500,a)};
g.h.iC=function(){this.G=!1;f1(this)};
g.h.aC=function(a){a.stopPropagation();this.hide()};
g.h.bC=function(a){a.stopPropagation();h1(this);this.w=!0;g.K(this.g,"iv-promo-collapsed-no-delay");this.B.start()};
g.h.destroy=function(){this.B.dispose();c1.prototype.destroy.call(this)};g.r(j1,g.QO);g.h=j1.prototype;g.h.sc=function(a,b){if(!l1(this.player.L().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.ZY(b);c&&p1(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&($0(this.g,b),X_(this.player)),!0}return null};
g.h.getOptions=function(){return l1(this.player.L().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Zm=function(){if(this.o){var a=g.cK(this.player).getVideoContentRect(!0);g.pg(this.o.element,a.width,a.height);g.eg(this.o.element,a.left,a.top)}if(this.g){var b=g.kK(this.player);a=this.g;b=b.width;g.L(a.B,"iv-drawer-small",426>=b);g.L(a.B,"iv-drawer-big",1280<=b)}};
g.h.SI=function(a){this.Zb(a.state);g.R(a.state,2)&&(this.Ij()&&this.iw()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.kq(!1))};
g.h.load=function(){g.QO.prototype.load.call(this);this.Zb(g.bK(this.player));this.D++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.FH,this,b,this.D),d=(0,g.x)(function(){this.w=null},this);
g.Wo()&&(c=q1(this,c));c={format:"XML",Wc:c,onError:d,pd:{}};a.isPharma&&(c.pd.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.L().D.get(b))&&r1(c,b);b=b&&(b.rl||b.ql);if(!a.al||b)a.Ed?m1(this,a.Ed,c):(this.l=(0,g.x)(this.wD,this,c),this.player.addEventListener("videodatachange",this.l));g.tK(this.player,this.o.element,4);this.Zm();(b=a.Fa&&a.Fa.cards&&a.Fa.cards.cardCollectionRenderer||null)&&Xoa(this,b);(b=joa(a))&&Yoa(this,b,a.videoId||null,a.eventId||null)};
g.h.Zb=function(a){a=!a.isCued()&&!g.R(a,1024);g.ru(this.i,a);g.ru(this.o,a)};
g.h.wD=function(a){var b=this.player.getVideoData();b.Ed&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),m1(this,b.Ed,a))};
g.h.unload=function(){g.UP(this.player.app,"annotations_module",void 0);g.Mb(this.B,function(a){a.destroy()});
this.C=null;this.g&&(this.g.destroy(),this.g=null,X_(this.player));this.G=!1;this.w&&(this.w.abort(),this.w=null);this.B={};this.i.hide();g.QO.prototype.unload.call(this);g.qu(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.FH=function(a,b,c){this.w=null;!o1(this,b,a)&&(a=g.tp(c)&&c.responseXML?c.responseXML:null)&&(p1(this,a),g.K(this.player.getRootNode(),"iv-module-loaded"))};
g.h.iy=function(a){a==this.player.getVideoData().videoId&&(this.loaded?Uoa(this):this.load())};
g.h.Ij=function(){return!!this.g&&this.g.isAvailable()};
g.h.iw=function(){this.Ij();return!!this.g&&this.g.w};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Ij();this.g&&(a?c?U0(this.g,c,b):U0(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):V0(this.g))};
g.h.kq=function(a,b){this.player.N(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.V=function(){this.player.L().D.unsubscribe("vast_info_card_add",this.iy,this);g.kn(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.I,b=0,c=a.length;b<c;b++)g.Xo(a[b]);this.I.length=0;g.QO.prototype.V.call(this)};g.dP.annotations_module=j1;g.dP.creatorendscreen=m0;})(_yt_player);
